name = "atelier-by-rita"
compatibility_date = "2026-08-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "atelier-rita-db"
database_id = "c5d8bf56-0e0d-4d75-b81b-e2c783eccac1"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "atelier-rita-r2"

[vars]
SITE_URL = "https://ritacamoesas.pt"
EMAIL_FROM = "reservas@ritacamoesas.pt"
RESERVA_PRAZO_HORAS = "24"
PAYMENT_MBWAY_PHONE = "9XXXXXXXX"
PAYMENT_IBAN = "PT50 XXXX XXXX XXXXXXXXXXX XX"
PAYMENT_ACCOUNT_HOLDER = "rita camoesas"